#set($pathImg="http://image.guihua.com/")
#set($pathSucai="http://static.guihua.com/") 
#set($pathXdlj="$!request.getContextPath()")
#set($loginUserId="$!session.getAttribute('haoguihua_login_session_user').id") 
#set($loginUserName="$!session.getAttribute('haoguihua_login_session_user').name") 
#set($loginUserIdentity="$!session.getAttribute('haoguihua_login_session_user').userIdentity") 
#set($talicaiPath="http://www.guihua.com/")
#if("$!menu" == "index")
#set($keywords="理财规划,投资理财,个人理财,家庭理财,在线理财网") 
#set($title="理财规划_理财投资_个人理财_家庭理财_在线理财--好规划网")
#set($description='好规划网（www.guihua.com）为您提供专业的在线理财规划及理财咨询服务。为您个人理财、家庭理财提供理财方案。"好规划奋斗版"是专属年轻奋斗人群的理财规划服务版本。')  
#set($csspath="http://static.guihua.com/css/index.css")
#set($jspath="http://static.guihua.com/js/index.js")
#end